specVersion: 0.2.0
name: RMRKXPLR
version: 0.1.0
description: 'A simple RMRK explorer for the Gitcoin GR12 hackathon'
repository: 'git@github.com:freespirit/rmrkxplr.git'

schema:
  file: ./schema.graphql

network:
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  endpoint: 'wss://kusama.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/dictionary-kusama'

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batch
            success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
            module: system
            method: remark
            success: true
